### PR TITLE
Update messages.js

### PR DESCRIPTION
**Pull request by christophmitterer**
Hi Tobias and Norbert,
first @tkupek > great job, I appreciate it very much what you developed!
I checked and updated the wording for EN, DE, IT in messages.js.

There might be some language issues in IT for 'EXPOSITION_ELEVATIONHI' and 'EXPOSITION_ELEVATIONLW'. 
@tkupek: How do you handle the difference between a numerical value for the elevation and the categorical value "tree line". This makes a difference for IT > al di sopra di 2200m vs. al di sopra del limite del bosco

Best regards, Christoph

### CODE REVIEW

**Comment by tkupek** [comment]
Hi Christoph,
thank you very much for your feedback and especially for your update of the translations.

It is extremely helpful and I already included and deployed the changes. Please take a note that I had to re-add the follow up question at `DANGER_LEVEL_INTRO_1`, as a follow up question is required (by Amazon & Google) for all responses that do not close the dialog session.

May I ask you a big favor? The translations for the intent definitions are still unchecked. You can find them here [https://github.com/tkupek/avalanche-forecast/tree/master/alexa/models](url). It would be wonderful if you can check them as well.

Again thanks and greetings,
Tobias

**Comment by christophmitterer** [comment]
Hi Tobias,
I certainly can do that, but can you please provide me a bit more explanation on the desired content of the files. I see that you use different wording for e.g. “Gefahrenstufe”. Does this have to be consistent, i.e. only one term allowed, or do you want to cover all possible synonyms and closely related terms.
In addition, is there a systematic approach on how you selected the geographical terms? For our Catalogue of Phrases we used a adopted DB on location names … maybe we could use that?
Cheers, Chris

**Comment by tkupek** [comment]
Hi Chris,
sorry if I missed out some background information.

The different variations are used to train the ML speech recognition model. Therefore we need to provide multiple options how the user can ask for specific things. E.g. the user can say 
> explain me the danger scale

as well as

> what is the danger scale

for the same intent.

Same logic goes for the locations. The main value is the one used for the Google Geoencoding, while synonyms are alternate ways the user can ask for.

Right now there is not really a systematic approach for the locations, I tried to include the biggest as well as well known places. It would definitely make sense to have a better approach on that. Right now the out of the box slot for locations does not recognize many of the Tyrolean valleys and villages, therefore we still need to provide a list of possible options. 

I have seen that Google lately increased their limits for entity entries, so we should not run into a restriction of maximum locations. (also Amazon has a limit of around 50k)
[https://cloud.google.com/dialogflow/quotas](url)

Can you somehow grant me access to your location name list or export them? Are they all geocodable via Google Geocoding?

Thanks again for your support, it is very appreciated!
Tobias

**Comment by christophmitterer** [comment]
Hi Tobias,
Got it, I will try to comment the stuff within the next days.
I will check, if our location names are geocodable via Google Geocoding. If yes, I can provide you with a table of location names.
Have a nice one, Chris

**Comment by tkupek** [comment]
Thanks Christoph!

**Comment by tkupek** [comment]
Hi Christoph! Any updates on this?
Norbert asked me to change the invocation word to "avalanche report" as it's the official wording. I will do so but before I resubmit to Google & Amazon it would be nice to have the final wording.

**Comment by christophmitterer** [comment]
Hi,
sorry for not replying, I have some problems with my back and will come back to you as soon as possible.
Ciao, Chris

**Comment by tkupek** [comment]
Hi there.
No problem, get well soon.
Tobias

**Comment by christophmitterer** [comment]
Hi Tobias,
instead of correcting your geo-location file names I sent you our TXT-Files in DE/EN/IT. They are consistent with used terminology of our Catalogue of Phrases (CoP) and  our naming in the base map of our website and most of them can be geo-located, as you can search for the locations within our map. 
The files have a Tag for every country and/or province. The tag starts with e.g. "Begin: Tyrol” and ends with e.g. “End: Tyrol”. Keep in mind that the CoP is also used by our colleagues in Switzerland and therefore also all Swiss geo-location names are included. 

Concerning changing the invocation > I agree with Norbert, would be really cool, if you change that one

Hope that helps.
If you have any question, just go ahead

**Comment by tkupek** [comment]
Hi Christoph,

I hope you are feeling better?
The list of geo-location names will probably improve the skill a lot. Thank you for this! Where exactly do I find the TXT files?

Btw, I am already working on the updated invocation name. Google Assistant is live, Alexa should follow in a few days.

Does the Swiss avalanche report only follows your CoP, or do they have an API as well?

Best,
Tobias

**Comment by christophmitterer** [comment]
yes, I am feeling better, but still recovering.
I just forgot to attach the files. Have a look and let me know if that is suitable for you.
Cheers, Christoph

**Comment by tkupek** [comment]
Hi again,

unfortunately I cannot see the file in GitHub.
Would you send it to me again to my private mail (mail@tkupek.eu)?

Thanks alot!
Tobias

**Pull request merged**
